global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8081']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8090']

  - job_name: 'expense-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['expense-service:8091']

  - job_name: 'budget-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['budget-service:8093']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8092']

  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-service:8094']
